on:
  push:
    branches:
      - main  # Change to your default branch if needed
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Decode SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem $EC2_USER@$EC2_HOST
          scp -i ec2-key.pem -r backend frontend $EC2_USER@$EC2_HOST:/home/$EC2_USER/react-app/

          ssh -i ec2-key.pem $EC2_USER@$EC2_HOST << 'EOF'
            # Navigate to frontend & build React app
            sudo apt update && sudo apt install -y build-essential sqlite3
            cd /home/ubuntu/react-app/frontend
            npm install
            npm run build
            mv dist ../backend/public  # Move build files to backend/public

            # Navigate to backend & install dependencies
            cd /home/ubuntu/react-app/backend || exit 1

            # Remove old dependencies and install fresh ones
            rm -rf node_modules package-lock.json
            npm install
            npm rebuild sqlite3 --build-from-source

            # Restart backend server with PM2
            sudo npm install -g pm2
            pm2 restart all || pm2 start server.js --name react-backend
            pm2 restart frontend-app || pm2 start "npx serve -s frontend/dist -l 3000" --name frontend-app

            pm2 save
            pm2 list
          EOF

    
      - name: Cleanup SSH Key
        run: rm -f ec2-key.pem
